<%

  user = ENV["RDS_USERNAME"]
  pass = ENV["RDS_PASSWORD"]
  host = ENV["RDS_HOSTNAME"] || 'localhost'
  port = ENV["RDS_PORT"] || 5432
  db   = ENV["RDS_DB_NAME"] || 'manifold_development'
  test_db   = ENV["RAILS_TEST_DB_NAME"] || 'manifold_test'

%>

common: &common
  adapter: postgresql
  host: <%= host %>
  encoding: unicode
  pool: 50
  port: <%= port %>
  user: <%= user %>
  database: <%= db %>
  password: "<%= pass %>"

production:
  <<: *common

demo:
  <<: *common

staging:
  <<: *common

development:
  <<: *common

test:
  <<: *common
  database: <%= test_db %><%= ENV["TEST_ENV_NUMBER"] %>
